name: cdc
channels:
  - conda-forge
  - defaults
  - https://conda.ccdc.cam.ac.uk
dependencies:
  - csd-python-api
  - python=3.9
  - rdkit
  - openbabel
  - oddt
  - boost-cpp
  - numpy
  - sphinx
  - sphinx_rtd_theme
  - swig
  - pymol-open-source
  - pip

